//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCEventUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCEventUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   インスタンスの作成をキャンセルしました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Abort_CreateInstance {
            get {
                return ResourceManager.GetString("Abort_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inviteを中断しました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Abort_Invite {
            get {
                return ResourceManager.GetString("Abort_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inviteを中断しています… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Aborting_Invite {
            get {
                return ResourceManager.GetString("Aborting_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更は保存されません．設定画面を閉じますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_DiscardSettingChanges {
            get {
                return ResourceManager.GetString("Confirm_DiscardSettingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションIDまたはインスタンスURLを入力してください． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_EmptyLocationIdOrUrl {
            get {
                return ResourceManager.GetString("Error_EmptyLocationIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   steam.exeのパスが指定されていません．
        ///ファイル(F)-&gt;設定-&gt;VRChat起動のsteam.exeのパスを設定してください． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_EmptySteamExePath {
            get {
                return ResourceManager.GetString("Error_EmptySteamExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションIDまたはインスタンスURLの形式が正しくありません． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_InvalidLocationIdOrUrl {
            get {
                return ResourceManager.GetString("Error_InvalidLocationIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールドIDまたはワールドURLの形式が正しくありません． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_InvalidWorldIdOrUrl {
            get {
                return ResourceManager.GetString("Error_InvalidWorldIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動ログインに失敗しました．ログインが必要です． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fail_AutoLogin {
            get {
                return ResourceManager.GetString("Fail_AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インスタンスの作成に失敗しました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fail_CreateInstance {
            get {
                return ResourceManager.GetString("Fail_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inviteに失敗しました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fail_Invite {
            get {
                return ResourceManager.GetString("Fail_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRChatの起動に失敗しました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fail_LauchVRChat {
            get {
                return ResourceManager.GetString("Fail_LauchVRChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに失敗しました．
        ///ユーザー名，パスワード（必要であれば二要素認証コード）が正しいことを確認してください． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fail_LogIn {
            get {
                return ResourceManager.GetString("Fail_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイル (*.csv)|*.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileFilter_CSV {
            get {
                return ResourceManager.GetString("FileFilter_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exeファイル (*.exe)|*.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileFilter_Exe {
            get {
                return ResourceManager.GetString("FileFilter_Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSONファイル (*.json)|*.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileFilter_JSON {
            get {
                return ResourceManager.GetString("FileFilter_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTitle_File {
            get {
                return ResourceManager.GetString("MenuTitle_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTitle_Setting {
            get {
                return ResourceManager.GetString("MenuTitle_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}として自動ログインしました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success_AutoLogIn {
            get {
                return ResourceManager.GetString("Success_AutoLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インスタンスを作成しました．
        ///サーバー地域：{0}
        ///公開範囲：{1}
        ///ワールドID：{2}
        ///インスタンスID：{3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success_CreateInstance {
            get {
                return ResourceManager.GetString("Success_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inviteに成功しました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success_Invite {
            get {
                return ResourceManager.GetString("Success_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にInviteを送信しました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success_InviteSentTo {
            get {
                return ResourceManager.GetString("Success_InviteSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}としてログインしました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success_Login {
            get {
                return ResourceManager.GetString("Success_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウトしました． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success_Logout {
            get {
                return ResourceManager.GetString("Success_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invite送信を中断中… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_AbortingInvite {
            get {
                return ResourceManager.GetString("Text_AbortingInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invite送信を中断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_AbortInvite {
            get {
                return ResourceManager.GetString("Text_AbortInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API呼び出し最小間隔（秒） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_APICallIntervalSec {
            get {
                return ResourceManager.GetString("Text_APICallIntervalSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Authentication {
            get {
                return ResourceManager.GetString("Text_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログをクリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ClearLog {
            get {
                return ResourceManager.GetString("Text_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インスタンスURLをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_CopyInstanceUrl {
            get {
                return ResourceManager.GetString("Text_CopyInstanceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インスタンスを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_CreateInstance {
            get {
                return ResourceManager.GetString("Text_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全般 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_General {
            get {
                return ResourceManager.GetString("Text_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_GroupList {
            get {
                return ResourceManager.GetString("Text_GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ID {
            get {
                return ResourceManager.GetString("Text_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーはInvite済みです． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_InviteSent {
            get {
                return ResourceManager.GetString("Text_InviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRChatで開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_LaunchInVRChat {
            get {
                return ResourceManager.GetString("Text_LaunchInVRChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRChat起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_LaunchVRChat_Setting {
            get {
                return ResourceManager.GetString("Text_LaunchVRChat_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_LocationId {
            get {
                return ResourceManager.GetString("Text_LocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Log {
            get {
                return ResourceManager.GetString("Text_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Logout {
            get {
                return ResourceManager.GetString("Text_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二要素認証コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_MFACode {
            get {
                return ResourceManager.GetString("Text_MFACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーにはInviteを送信していません． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_NotSentInviteYet {
            get {
                return ResourceManager.GetString("Text_NotSentInviteYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_OK {
            get {
                return ResourceManager.GetString("Text_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン状態を保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SaveAuthCookies {
            get {
                return ResourceManager.GetString("Text_SaveAuthCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SelectFile {
            get {
                return ResourceManager.GetString("Text_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inviteを送信中：{0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SendingInvite {
            get {
                return ResourceManager.GetString("Text_SendingInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inviteを送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SendInvite {
            get {
                return ResourceManager.GetString("Text_SendInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信先設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SendTargetSetting {
            get {
                return ResourceManager.GetString("Text_SendTargetSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Setting {
            get {
                return ResourceManager.GetString("Text_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   steam.exeのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SteamExePath {
            get {
                return ResourceManager.GetString("Text_SteamExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーはInvite先のインスタンスにいます． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UserInInstance {
            get {
                return ResourceManager.GetString("Text_UserInInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーはスタッフです． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UserIsStaff {
            get {
                return ResourceManager.GetString("Text_UserIsStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーリストファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UserListFile {
            get {
                return ResourceManager.GetString("Text_UserListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_Username {
            get {
                return ResourceManager.GetString("Text_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーはInvite先のインスタンスにいません． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UserNotInInstance {
            get {
                return ResourceManager.GetString("Text_UserNotInInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーはオフラインです． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UserOffline {
            get {
                return ResourceManager.GetString("Text_UserOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRモードを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UseVRMode {
            get {
                return ResourceManager.GetString("Text_UseVRMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Joinを待っています… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_WaitingJoin {
            get {
                return ResourceManager.GetString("Text_WaitingJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールドID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_WorldId {
            get {
                return ResourceManager.GetString("Text_WorldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールド・インスタンス設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_WorldInstanceSetting {
            get {
                return ResourceManager.GetString("Text_WorldInstanceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   steam.exeファイルを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_SelectSteamExeFile {
            get {
                return ResourceManager.GetString("Title_SelectSteamExeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーリストファイル選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_SelectUserListFile {
            get {
                return ResourceManager.GetString("Title_SelectUserListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションID/インスタンスURL
        ///
        ///「インスタンスを作成」ボタンを押すとインスタンスが作成され自動入力されます．
        ///
        ///インスタンスURL（例：https://vrchat.com/home/launch?worldId=wrld_ba913a96-fac4-4048-a062-9aa5db092812&amp;amp;instanceId=00000~region(jp)）
        ///または，ワールドID:インスタンスID（例：wrld_ba913a96-fac4-4048-a062-9aa5db092812:00000~region(jp)）のいずれかの形式で入力してください． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_LocationIdOrUrl {
            get {
                return ResourceManager.GetString("Tooltip_LocationIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールドID/ワールドURL
        ///
        ///ワールドID（例：wrld_ba913a96-fac4-4048-a062-9aa5db092812）または，
        ///ワールドURL（例：https://vrchat.com/home/world/wrld_ba913a96-fac4-4048-a062-9aa5db092812）
        ///のいずれかの形式で入力してください． に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_WorldIdOrUrl {
            get {
                return ResourceManager.GetString("Tooltip_WorldIdOrUrl", resourceCulture);
            }
        }
    }
}
